### ISSUE TITLE
 please support remote folder for imap too

### ISSUE THREAD

**Issue by internethering** [PF4Public/fetchmail#10]
like https://github.com/PF4Public/fetchmail/issues/4 fetchmail support this for IMAP too :)

**Comment by PF4Public** [comment]
It should work for imap. In fact it should work _only_ for imap and there is `fetchmail_toggle_folder` in js, which hides "folder" field otherwise.

**Comment by internethering** [comment]
sry, was too fast with my removing of the line. But it works not for me.

**Comment by PF4Public** [comment]
Please make localization edits a separate pull request, I would gladly accept it.
What browser are you using?
PS: haven't you forgot to enable the feature? I made it `false` by default on purpose.

**Comment by internethering** [comment]
ups, it was on false. I got confused because I copied the `config.inc.php` from `./config/` to `./` and changed this in the copy, because in all others plugin the config file is located at the root folder of the plugin.

**Comment by PF4Public** [comment]
I was considering moving that up. Now I see that is important :) Opened #13 for that

**Comment by PF4Public** [comment]
I assume I may close this issue now.
