### ISSUE TITLE
SQL Statement

### ISSUE THREAD

**Issue by derritter88** [PF4Public/fetchmail#16]
Hello there,

don't know if this is a bug but when I have put in my fetchmail credentials for an external account the SQL statement used 'pop3' instead of 'POP3' and this caused a MySQL exception due to case sensitive.

Kind regards,
Mathias

**Comment by PF4Public** [comment]
Have you tried to edit fetchmail.php to make this code:

> ```
>   $input_fetchmailprotocol->add ( array (
>             'IMAP',
>             'POP3' 
>     ), array (
>             'imap',
>             'pop3' 
>     ) );
> ```

become this:

> ```
>   $input_fetchmailprotocol->add ( array (
>             'IMAP',
>             'POP3' 
>     ), array (
>             'IMAP',
>             'POP3' 
>     ) );
> ```

Does this fix the issue for you?
