### ISSUE TITLE
Show folder for IMAP accounts in list

### ISSUE THREAD

**Issue by c-holtermann** [PF4Public/fetchmail#17]
When a folder is selected for IMAP Accounts it would be helpful if this information would be shown in the list view.

**Comment by PF4Public** [comment]
Is it the list where all of added accounts are shown?

**Comment by c-holtermann** [comment]
yes.

![fetchmail3](https://cloud.githubusercontent.com/assets/341156/18257512/297112a0-73c5-11e6-8eae-0b127a183a75.png)
