### ISSUE TITLE
Information for IMAP folder not shown when editing 

### ISSUE THREAD

**Issue by c-holtermann** [PF4Public/fetchmail#18]
When creating a new IMAP fetch it is possible to select a folder. 
![fetchmail1](https://cloud.githubusercontent.com/assets/341156/18247096/a0363a1e-7370-11e6-980f-844c730d8d8c.png)
When editing the entry later the field folder is not being shown. 
![fetchmail2](https://cloud.githubusercontent.com/assets/341156/18247097/a0373f68-7370-11e6-9270-37696ad39364.png)

The database contains the field and it works. It's just not possible to see or edit it.

**Comment by PF4Public** [comment]
Sorry, my bad :(
