### ISSUE TITLE
email fetch  issue for pop.gmail.com

### ISSUE THREAD

**Issue by aniljalela** [PF4Public/fetchmail#27]
Hi,

We are able to fetch emails from the private domain but not able to from pop.gmail.com. we have already made necessary changes into Gmail account (enable pop)Please let me know if any special configuration required for this. we use fetchmail.Pl latest reversion file as per your guideline.

Thank You

**Comment by PF4Public** [comment]
Hello

No special configuration necessary for POP. Maybe SSL should be enabled for Google POP. Your firewall might interfere or something else. 
Fetchmail log messages might give a clue. It would be helpful if you could provide me with them.

By the way, why didn't you consider using IMAP at the first place?

**Comment by aniljalela** [comment]
Hi ,
for Gmail  need some addition configuration.

1- Sign into the  Gmail account first ( the one you are trying to fetch mail from )

2 -  you may need to Enable less-secure Apps for that account >> https://www.google.com/settings/security/lesssecureapps

3 - Then go here: https://accounts.google.com/b/0/DisplayUnlockCaptcha

config you need to create on your server 

poll pop.gmail.com protocol POP3 and port 995: user "gmail@gmail.com" there with password "xxxxxxxx" is xxxx@xxxxxxxxxx.com here options fetchall, keep, ssl, sslcertck, idle
 
Thank You
