### ISSUE TITLE
Fetchmail not fetching on CPANEL/Roundcube installation

### ISSUE THREAD

**Issue by bbicudo** [PF4Public/fetchmail#28]
I've installed the plugin following you rstep-by-step, but i'm still unable to fetch emails from other ISPs (yahoo, google, hotmail, etc).

No errors showed up on any logs. Do u have any idea where to check for errors? :)

Also thanks for the awesome work on this plugin 👍

**Comment by bbicudo** [comment]
Don't know if it helps, but running fetchmail -v manually giver me the following message:

fetchmail: no mailservers have been specified.

**Comment by PF4Public** [comment]
Can't tell you exactly what is wrong, given so little information, but here are points to test first:
* Is fetchmail.pl added to `cron` schedule?
* Is fetchmail.pl configured properly?
* Does fetchmail.pl have access to your database?
* Is fetchmail.pl script executable?
* Are settings among fetchmail.pl and roundcube consistent?

Fetchmail should write to your `mail.log` or `mail.err` logfiles. If it does not, maybe it is not started by cron in the first place?

**Comment by bbicudo** [comment]
Let's answer the questions:

Yes
Yes
Yes
Yes
Yes

I can't find neither mail.log nor mail.err, but i checked that the script is started by cron.

Can this be anything related to the fact that roundcube itself is installed under Cpanel?

Thanks for the help so far 💯

**Comment by bbicudo** [comment]
Updating:

Can this also be related to mailman being used with postfix admin?

**Comment by PF4Public** [comment]
Please try running fetchmail.pl script manually. *Not* fetchmail itself, but a fetchmail.pl script you configured with your roundcube database. Be sure to have configured any mail account in roundcube to fetch mail for and manually edit that database entry so that the `date` field to be guaranteed in far past.

**Comment by PF4Public** [comment]
I will close this for no reply.
