### ISSUE TITLE
elastic skin is not working with fetchmail

### ISSUE THREAD

**Issue by smhessenauer** [PF4Public/fetchmail#30]
With the new default skin of Roundcube 'elastic' or 'classic' the fetchmail plugin is not working.
error message in Roundcube error log:

`PHP Error: Error loading template for fetchmail.fetchmail in /usr/share/roundcube/program/include/rcmail_output_html.php on line 755 (GET /?_task=settings&_action=plugin.fetchmail)`

It still works with the skin 'larry'

**Comment by PF4Public** [comment]
Is 'elastic' something that is only recently added?

**Comment by smhessenauer** [comment]
According to the changelog this new repsonsive skin was added for 1.4.0, so in November last year.

**Comment by PF4Public** [comment]
Oh, right. I've just checked my mail server, where this plugin is still used. Roundcube is 1.3.8 there.
Obviously, I haven't implemented this new skin since then.

**Comment by smhessenauer** [comment]
Seems not too difficult to adapt to the new skin. See my commits here: https://github.com/smhessenauer/fetchmail/commits/elastic_skin

**Comment by PF4Public** [comment]
If you can make it and verify, that it is working well, do a PR, I'll happily accept it and publish next release.

Unfortunately, I didn't have the time to do it myself, and still don't.

**Comment by smhessenauer** [comment]
Ok, I’ll look into it.

**Comment by smhessenauer** [comment]
Pull request raised. If it can be merged, we can close here.

**Comment by PF4Public** [comment]
Thanks for your efforts

**Comment by smhessenauer** [comment]
welcome :)
