### ISSUE TITLE
Fetchmail -Roundcube plugin on Plesk server  

### ISSUE THREAD

**Issue by SreejithChandra** [PF4Public/fetchmail#36]
Hi,

We have installed the roundcube plugin
imported the initial.sql and .sql file inside mysql directory 
created cron. New account is added in the Roundcube -> Settings -> Fetchmail. 

It is also showing on roundcubemail.fetchmail table. 

but emails are not fetching.

**Comment by SreejithChandra** [comment]
UPDATE: Fetchmail.pl is placed at /var/qmail/mailnames/
Fetchmail.pl config is set to mysql and updated connection with roundcubemail database and roundcube username and password. 

Am I missing something?

**Comment by SreejithChandra** [comment]
No errors are logged anywhere when running the fetchmail.pl script. Checked mail.log, mail.err and syslog.

**Comment by PF4Public** [comment]
> No errors are logged anywhere when running the fetchmail.pl script. Checked mail.log, mail.err and syslog.

What is your fetch period in settings? There could be no logs if time interval is not achieved yet.

**Comment by SreejithChandra** [comment]
Sorry for delay. The fetch period was default in the first place. But we have changed it to 5 minutes too

**Comment by PF4Public** [comment]
To debug this you may change the `date` value of the record in DB to some time in past and run `fetchmail.pl` manually. If there are any errors, they should be printed out.

**Comment by SreejithChandra** [comment]
Can I paste fetchmail.pl script here so that you can verify settings are correct?

**Comment by SreejithChandra** [comment]
Please check this. 
https://pastebin.pl/view/375ebe43
Also note, we dont have PostfixAdmin installed

**Comment by SreejithChandra** [comment]
Also, the server doesnt have the patch mentioned in the .pl file 
$configfile = "/etc/fetchmail-all/config";

**Comment by PF4Public** [comment]
> Also note, we dont have PostfixAdmin installed

You don't have to.

Did you try running `fetchmail.pl` manually like I've suggested earlier?

> To debug this you may change the `date` value of the record in DB to some time in past and run `fetchmail.pl` manually. If there are any errors, they should be printed out.

> Please check this.
> https://pastebin.pl/view/375ebe43

If your password _actually_ is "password", then it it looks fine.



> Also, the server doesnt have the patch mentioned in the .pl file
> $configfile = "/etc/fetchmail-all/config";

That's probably because you

> dont have PostfixAdmin installed

**Comment by SreejithChandra** [comment]
Thank you for the explanation. Yes we have tried running the script manually and it is not fetching any emails. Is there any way to generate error atleast? The script doesnt even return any errors.

**Comment by PF4Public** [comment]
> Yes we have tried running the script manually

Did you change the `date` in DB. It is the third time I'm writing this. I would like to not repeat myself.

**Comment by SreejithChandra** [comment]
I am extremely sorry for not answering all questions. OMG. Thanks it worked. Changed the date to 7th of this month and the emails are now showing. 

Just clarifying things, So, the cron or manually running the script should fetch new emails from now on. Right?

**Comment by PF4Public** [comment]
```perl
        $sql_cond = "active = 't' AND unix_timestamp(now())-unix_timestamp(date)";
…
        WHERE $sql_cond  > poll_time*60
```
It should be comparing the `date` with `poll_time*60` and grabbing mails if the time has been reached.

**Comment by PF4Public** [comment]
Feel free to close this bug if it is resolved.

**Comment by SreejithChandra** [comment]
Thanks for sorting. Fixed it
